### ISSUE TITLE
Build failures with mtl-2.3

### ISSUE THREAD

**Issue by sjakobi** [DanBurton/tardis#13]
```
src/Control/Monad/Trans/Tardis.hs:119:10: error:
    Not in scope: type constructor or class ‘MonadFix’
    Perhaps you meant ‘MonadFail’ (imported from Prelude)
    |
119 | instance MonadFix m => Monad (TardisT bw fw m) where
    |          ^^^^^^^^
```

I'm seeing similar failures in all Hackage releases of `tardis`.

As a Hackage trustee I have created revisions that should prevent users from encountering these errors. See e.g. https://hackage.haskell.org/package/tardis-0.4.3.0/revisions/.

**Comment by DanBurton** [comment]
Thanks for the report. I've addressed this in https://github.com/DanBurton/tardis/commit/e69aa52058acade55776a0bc265fd33d1faed329 and uploaded a new version of the package
