### ISSUE TITLE
Expose TardisT constructor or provide mapTardisT

### ISSUE THREAD

**Issue by vizziv** [DanBurton/tardis#5]
(I hope this is still the right repository; I see it hasn't been active for a while.)

I want to write an instance*
```
instance (MonadReader r m, MonadFix m) => MonadReader r (TardisT m) where
  ask = lift ask
  reader = lift . reader
  local f m = TardisT $ local f . runTardisT m
```
... but the `TardisT` constructor isn't public. For this purpose, it would also suffice to expose a function `mapTardisT` analogous to `mapStateT`.
```
mapTardisT :: (m ((bw, fw), a) -> n ((bw, fw), b)) ->
              TardisT bw fw m a -> TardisT bw fw n b
mapTardisT f m = TardisT $ f . runTardisT m
```
I'm not sure if the omission of at least one of these options is intentional or not, but I think they don't hurt to have and make the library a bit more versatile.

*Well, not quite: it's wrapped in a newtype to avoid the orphan instance problem, but it's basically the same.

**Comment by DanBurton** [comment]
The omission of the constructor was unintentional, thanks for catching that! And apparently I forgot to  release version 0.4.0.0, but version 0.4.1.0 is up on hackage now. It exports the constructor and `mapTardisT`.
