### ISSUE TITLE
Indexed Tardis monad?

### ISSUE THREAD

**Issue by Taneb** [DanBurton/tardis#7]
I'm using an indexed variant of `Tardis`, `newtype ITardis bw fw i j a = ITardis {runITardis :: (bw j, fw i) -> (a, (bw i, fw j))}` in a personal project of mine, and I'd like to make it available to others.

The natural place to put it would be in this library, however it's adding a new dependency (on `indexed`) and doesn't actually use anything in here.

I'd like to know if you think it would fit better in here or as its own library.

Thanks!

**Comment by DanBurton** [comment]
Sounds interesting! I'm inclined to recommend having it as its own library.
